spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/todolist?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password:

